### Create BP
POST http://localhost:4004/odata/v4/api-business-partner/A_BusinessPartner
Content-Type: application/json

{
  "BusinessPartner": "17100008",
  "BusinessPartnerFullName": "Testing BP x1",
  "BusinessPartnerIsBlocked": true,
  "Language": "EN"
}
### Edit BP
PATCH http://localhost:4004/odata/v4/api-business-partner/A_BusinessPartner('17100008')
Content-Type: application/json

{
    "BusinessPartnerIsBlocked": false
}